// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYDRU3aWu7z3q7bqOwTowPLjEBI9BTKA',
    appId: '1:757434109730:web:b8c7144b7e6a6ef3efdf7b',
    messagingSenderId: '757434109730',
    projectId: 'candidapp-10368',
    authDomain: 'candidapp-10368.firebaseapp.com',
    storageBucket: 'candidapp-10368.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaETJhUpysjGSi8FXk--k6w8AC7hF-ATg',
    appId: '1:757434109730:android:df5e45ae07fa3fffefdf7b',
    messagingSenderId: '757434109730',
    projectId: 'candidapp-10368',
    storageBucket: 'candidapp-10368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6MyGpdhEo0wY_7OIW4hWWkLwMzeOsblE',
    appId: '1:757434109730:ios:475f4623dd7cfaa1efdf7b',
    messagingSenderId: '757434109730',
    projectId: 'candidapp-10368',
    storageBucket: 'candidapp-10368.firebasestorage.app',
    iosBundleId: 'com.example.candidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6MyGpdhEo0wY_7OIW4hWWkLwMzeOsblE',
    appId: '1:757434109730:ios:475f4623dd7cfaa1efdf7b',
    messagingSenderId: '757434109730',
    projectId: 'candidapp-10368',
    storageBucket: 'candidapp-10368.firebasestorage.app',
    iosBundleId: 'com.example.candidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCYDRU3aWu7z3q7bqOwTowPLjEBI9BTKA',
    appId: '1:757434109730:web:a8306536f4c777e7efdf7b',
    messagingSenderId: '757434109730',
    projectId: 'candidapp-10368',
    authDomain: 'candidapp-10368.firebaseapp.com',
    storageBucket: 'candidapp-10368.firebasestorage.app',
  );
}
